const USER_NAME = "USER_NAME";
const GET_PERSONAS = "GET_PERSONAS";
const ADD_FRIEND = "ADD_FRIEND"
const DELETE_FRIEND = "DELETE_FRIEND"

export { USER_NAME, GET_PERSONAS, DELETE_FRIEND, ADD_FRIEND };
